insert into user_groups (id, name) values (1, 'erat');
insert into user_groups (id, name) values (2, 'nec');
insert into user_groups (id, name) values (3, 'pellentesque volutpat');
insert into user_groups (id, name) values (4, 'vestibulum rutrum rutrum');
insert into user_groups (id, name) values (5, 'lorem ipsum dolor');
insert into user_groups (id, name) values (6, 'tempus vivamus in');
insert into user_groups (id, name) values (7, 'vulputate');
insert into user_groups (id, name) values (8, 'aenean');
insert into user_groups (id, name) values (9, 'sem praesent id');
insert into user_groups (id, name) values (10, 'tincidunt lacus');
insert into user_groups (id, name) values (11, 'blandit lacinia');
insert into user_groups (id, name) values (12, 'magna at');
insert into user_groups (id, name) values (13, 'dui vel');
insert into user_groups (id, name) values (14, 'porttitor lacus');
insert into user_groups (id, name) values (15, 'aliquet maecenas');
insert into user_groups (id, name) values (16, 'lorem');
insert into user_groups (id, name) values (17, 'odio donec vitae');
insert into user_groups (id, name) values (18, 'elit sodales');
insert into user_groups (id, name) values (19, 'massa volutpat convallis');
insert into user_groups (id, name) values (20, 'at nibh');
insert into user_groups (id, name) values (21, 'hac');
insert into user_groups (id, name) values (22, 'eu');
insert into user_groups (id, name) values (23, 'nulla mollis molestie');
insert into user_groups (id, name) values (24, 'semper');
insert into user_groups (id, name) values (25, 'hac habitasse');