services:
  php:
    build: Docker/.
    ports:
      - "8000:80"
      - "9003:9003"
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DB: db
    restart: always
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - user-usergroup-docker

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    restart: always
    networks:
      - user-usergroup-docker

volumes:
  db_data: { }
networks:
  user-usergroup-docker: